---
# tasks file for mysql
- name: Instala o mysql
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - mysql-server
    - mysql-common
    - python-mysqldb

- name: Garante que o serviço está habilitado
  service: name=mysql state=started enabled=yes

- name: Testa a conexão com o banco e se for necessário, cria a senha do root
  shell: "mysql -u root"
  register: conexao
  ignore_errors: true

- name: Cria a senha do root
  mysql_user:
    name: root
    password: "{{ senha }}"
    state: present
  when: conexao|success

# - name: Verifica se eh necessario a alteracao do bind-address
#   shell: grep "bind-address = 0.0.0.0" /etc/mysql/my.cnf
#   register: bind_address
#   ignore_errors: true

- name: Altera o parametro "bind-address"
  lineinfile:
    path: /etc/mysql/my.cnf
    regexp: ^bind-address
    line: bind-address = 0.0.0.0
  # when: bind_address|failed
  notify: Restart mysql