---
# tasks file for zabbix-web
- name: Instala o zabbix-frontend
  apt: name=zabbix-frontend-php state=present update_cache=yes

- name: Copia o arquivo apache.conf
  copy:
    src: apache.conf
    dest: /etc/zabbix/apache.conf
  notify: Restart Apache